fix: Allow failovers of cluster attributes for active-active domains (#7549)
<!-- Describe what has changed in this PR -->
**What changed?**

Modified the FailoverDomain request mapper to allow a null
ActiveClusterName to be specified. In turn, this allows active-active
domains to only modify their cluster attributes without changing the
default ActiveClusterName.

<!-- Tell your future self why have you made these changes -->
**Why?**

Active-Active domains are partitioned by 'cluster attributes'. Each
cluster attribute operates as its own independent active-passive domain
within the larger domain. As they are independent, it needs to be
possible to failover attributes without amending the global default for
a given domain. This fix brings the FailoverDomain endpoint inline with
the expected behavior for an active-active domain.

Because the proto mapper was assigning a non-null string pointer when
nil was passed to the API the later validateFailoverRequest functions
were treating this as the specification of a null ActiveClusterName
(which is invalid).


<!-- How have you verified this change? Tested locally? Added a unit
test? Checked in staging env? -->
**How did you test it?**

Added unit tests: `go test -v ./common/types/mapper/proto -run
TestFailoverDomainRequest`

Ran integration tests:

```bash
// Before fix
./cadence --domain test25 --transport grpc --address localhost:7833 domain failover --active_clusters location.london:cluster1
Error: Operation FailoverDomain failed.
Error details:
  ActiveClusterName is required for all global domains.

// After fix
./cadence --domain test25 --transport grpc --address localhost:7833 domain failover --active_clusters location.london:cluster1
Domain test25 successfully failed over.
```

Also tested on our canary domains in staging. 

<!-- Assuming the worst case, what can be broken when deploying this
change to production? -->
**Potential risks**

N/A

<!-- Is it notable for release? e.g. schema updates, configuration or
data migration required? If so, please mention it, and also update
CHANGELOG.md -->
**Release notes**

N/A

<!-- Is there any documentation updates should be made for config,
https://cadenceworkflow.io/docs/operation-guide/setup/ ? If so, please
open an PR in https://github.com/cadence-workflow/cadence-docs -->
**Documentation Changes**

N/A